version: '3'

services: 
  redis:
    image: redis:latest
  api:
    build: 
      context: ./server
    ports: 
      - "4000:4000"
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379